# Generated by Django 4.2.2 on 2023-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0004_remove_article_code_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='day',
            field=models.DateField(auto_now=True, verbose_name='稼働日'),
        ),
    ]
