# Generated by Django 4.2.2 on 2023-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0005_article_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='article',
            name='day',
            field=models.DateField(verbose_name='稼働日'),
        ),
    ]
