# Generated by Django 4.2.2 on 2023-12-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0006_article_name_alter_article_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
