# Generated by Django 4.2.2 on 2023-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0007_article_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='car_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='車両No'),
        ),
        migrations.AddField(
            model_name='article',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='終業時間'),
        ),
        migrations.AddField(
            model_name='article',
            name='oil',
            field=models.IntegerField(blank=True, null=True, verbose_name='オイル'),
        ),
        migrations.AddField(
            model_name='article',
            name='oiling',
            field=models.IntegerField(blank=True, null=True, verbose_name='給油'),
        ),
        migrations.AddField(
            model_name='article',
            name='oiling2',
            field=models.IntegerField(blank=True, null=True, verbose_name='給油'),
        ),
        migrations.AddField(
            model_name='article',
            name='weather',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='天気'),
        ),
        migrations.AlterField(
            model_name='article',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='稼働日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='運転者名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='始業時間'),
        ),
    ]
