# Generated by Django 4.2.2 on 2023-12-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0008_article_car_number_article_end_article_oil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='本文'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='posts',
        ),
    ]
