# Generated by Django 4.2.2 on 2024-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0009_article_created_at_article_text_alter_article_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='始業時間'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考欄'),
        ),
    ]
