# Generated by Django 4.2.2 on 2024-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0011_alter_article_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='car_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='車両No'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oil',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='オイル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oiling',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='給油'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oiling2',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='給油'),
        ),
    ]
