# Generated by Django 4.2.2 on 2024-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0012_alter_article_car_number_alter_article_oil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='oil',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='オイル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oiling',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='給油'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oiling2',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='給油'),
        ),
    ]
