# Generated by Django 4.2.2 on 2024-01-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0013_alter_article_oil_alter_article_oiling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='car_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='車両No'),
        ),
    ]
