# Generated by Django 4.2.2 on 2024-01-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0015_alter_article_created_at_alter_article_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'アプリモデル'},
        ),
    ]
