# Generated by Django 4.2.2 on 2024-01-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0016_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'verbose_name'},
        ),
    ]
