# Generated by Django 4.2.2 on 2024-01-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0017_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=1705028233.4848511, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
