# Generated by Django 4.2.2 on 2024-01-12 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0018_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
