# Generated by Django 4.2.2 on 2024-01-12 05:50

import daily_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0024_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=daily_report.models.Article.id_create, max_length=255, primary_key=True, serialize=False),
        ),
    ]
