# Generated by Django 4.2.2 on 2024-01-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0027_alter_article_created_at_alter_article_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '投稿一覧'},
        ),
    ]
